from typing import List, Optional
from pydantic import BaseModel, Field

class TestPlan(BaseModel):
    __test__ = False
    """Structured Test Plan generated by LLM from a requirement."""
    feature_name: str = Field(description="Name of the feature being tested.")
    objective: str = Field(description="Objective of the test plan.")
    scope: str = Field(description="Scope of testing.")
    assumptions: List[str] = Field(default_factory=list, description="Any assumptions made.")
    testing_approach: str = Field(description="The general approach for testing.")
    test_types: List[str] = Field(default_factory=list, description="Types of tests to be executed.")
    risks: List[str] = Field(default_factory=list, description="Potential risks.")
    dependencies: List[str] = Field(default_factory=list, description="System or test dependencies.")
    environment_requirements: str = Field(description="Requirements for the test environment.")
    out_of_scope_items: List[str] = Field(default_factory=list, description="Items not covered by this test plan.")
    api_testing_strategy: Optional[str] = Field(default=None, description="Strategy for testing API endpoints, if applicable.")
    performance_criteria: Optional[str] = Field(default=None, description="Criteria for performance testing, if applicable.")
