from typing import List, Any, Dict, Optional
from pydantic import BaseModel, Field

class TestCase(BaseModel):
    __test__ = False
    """Structured Test Case generated by LLM."""
    test_case_id: str = Field(description="Unique identifier for the test case (e.g., TC-001).")
    title: str = Field(description="Title of the test case.")
    description: str = Field(description="Detailed description of what the test verifies.")
    preconditions: List[str] = Field(default_factory=list, description="Preconditions required before execution.")
    test_data: Dict[str, Any] = Field(default_factory=dict, description="Test data inputs required.")
    steps: List[str] = Field(default_factory=list, description="Execution steps.")
    expected_result: str = Field(description="The expected outcome of the test.")
    test_type: str = Field(description="The type of test (e.g., Positive, Negative, Boundary, Edge Case, Security, API, Performance).")
    priority: str = Field(description="Priority of the test (e.g., High, Medium, Low).")
    severity: str = Field(description="Severity if this test fails (e.g., Critical, Major, Minor).")
    automation_possible: bool = Field(description="Whether this test can be automated using PyTest.")
    tags: List[str] = Field(default_factory=list, description="Tags for categorization.")
    api_endpoint: Optional[str] = Field(default=None, description="The API endpoint being tested, if applicable.")
    performance_threshold: Optional[str] = Field(default=None, description="Performance threshold (e.g., <200ms latency), if applicable.")
    code_snippet: Optional[str] = Field(default=None, description="The PyTest code snippet specifically for this test case.")
    
class TestSuite(BaseModel):
    """Collection of multiple Test Cases."""
    test_cases: List[TestCase] = Field(description="List of comprehensive test cases covering the requirements.")
