"""
Test Template Module
Generates test code from test case specifications.
"""

from typing import Dict, List, Any
from pathlib import Path


class TestTemplate:
    """
    Generates test code using templates.
    """
    
    def __init__(self):
        self.frameworks = {
            'pytest': self._pytest_template,
            'unittest': self._unittest_template
        }
    
    def render(
        self,
        source_file: str,
        test_cases: List[Dict[str, Any]],
        framework: str = 'pytest'
    ) -> str:
        """
        Render test code from test cases.
        
        Args:
            source_file: Path to source file being tested
            test_cases: List of test case specifications
            framework: Test framework to use
            
        Returns:
            Generated test code
        """
        template_func = self.frameworks.get(framework, self._pytest_template)
        return template_func(source_file, test_cases)
    
    def _pytest_template(
        self,
        source_file: str,
        test_cases: List[Dict[str, Any]]
    ) -> str:
        """Generate pytest test code."""
        source_path = Path(source_file)
        module_name = source_path.stem
        
        # Header
        code = f'''"""
Generated test cases for {source_path.name}
Auto-generated by AI Test Generator
"""

import pytest
from {module_name} import *


'''
        
        # Group test cases by function
        functions = {}
        for test_case in test_cases:
            func_name = test_case.get('function', 'unknown')
            if func_name not in functions:
                functions[func_name] = []
            functions[func_name].append(test_case)
        
        # Generate tests for each function
        for func_name, cases in functions.items():
            code += f"# Tests for {func_name}\n\n"
            
            for i, test_case in enumerate(cases):
                code += self._generate_pytest_test_function(test_case, i)
                code += "\n\n"
        
        # Add fixtures if needed
        code += self._generate_fixtures()
        
        return code
    
    def _generate_pytest_test_function(
        self,
        test_case: Dict[str, Any],
        index: int
    ) -> str:
        """Generate a single pytest test function."""
        func_name = test_case.get('function', 'unknown')
        test_type = test_case.get('type', 'general')
        description = test_case.get('description', '')
        params = test_case.get('params', {})
        expected = test_case.get('expected', 'success')
        
        # Generate test function name
        test_name = f"test_{func_name}_{test_type}_{index}"
        test_name = test_name.replace(' ', '_').replace('-', '_')
        
        code = f'def {test_name}():\n'
        code += f'    """{description}"""\n'
        
        # Generate test body based on expected outcome
        if 'raises' in expected or 'exception' in test_type.lower():
            # Exception test
            exception_type = self._extract_exception_type(expected, test_case)
            code += f'    with pytest.raises({exception_type}):\n'
            code += f'        {func_name}('
            code += self._format_params(params)
            code += ')\n'
        
        elif expected == 'success' or expected == 'boundary_check':
            # Regular assertion test
            code += f'    result = {func_name}('
            code += self._format_params(params)
            code += ')\n'
            code += '    assert result is not None\n'
            
            # Add type check if return type is known
            if test_case.get('return_type'):
                code += f'    assert isinstance(result, {test_case["return_type"]})\n'
        
        elif expected == 'null_handling':
            # Null handling test
            code += f'    result = {func_name}('
            code += self._format_params(params)
            code += ')\n'
            code += '    # Should handle None gracefully\n'
            code += '    assert True  # Customize this assertion\n'
        
        else:
            # Generic test
            code += f'    result = {func_name}('
            code += self._format_params(params)
            code += ')\n'
            code += '    # TODO: Add appropriate assertions\n'
            code += '    assert True\n'
        
        return code
    
    def _extract_exception_type(
        self,
        expected: str,
        test_case: Dict[str, Any]
    ) -> str:
        """Extract exception type from expected value."""
        if 'raises_' in expected:
            return expected.replace('raises_', '')
        
        # Check if function raises specific exceptions
        raises = test_case.get('raises', [])
        if raises:
            return raises[0]
        
        return 'Exception'
    
    def _format_params(self, params: Dict[str, Any]) -> str:
        """Format parameters for function call."""
        if not params:
            return ''
        
        param_strs = []
        for key, value in params.items():
            if isinstance(value, str):
                param_strs.append(f'{key}="{value}"')
            elif value is None:
                param_strs.append(f'{key}=None')
            elif isinstance(value, float) and value != value:  # NaN check
                param_strs.append(f'{key}=float("nan")')
            elif isinstance(value, float) and value == float('inf'):
                param_strs.append(f'{key}=float("inf")')
            elif isinstance(value, float) and value == float('-inf'):
                param_strs.append(f'{key}=float("-inf")')
            else:
                param_strs.append(f'{key}={repr(value)}')
        
        return ', '.join(param_strs)
    
    def _generate_fixtures(self) -> str:
        """Generate common pytest fixtures."""
        return '''
# Fixtures

@pytest.fixture
def sample_data():
    """Provide sample test data."""
    return {
        'test_string': 'sample',
        'test_int': 42,
        'test_list': [1, 2, 3],
        'test_dict': {'key': 'value'}
    }


@pytest.fixture
def mock_dependencies():
    """Mock external dependencies."""
    # Add your mocks here
    pass
'''
    
    def _unittest_template(
        self,
        source_file: str,
        test_cases: List[Dict[str, Any]]
    ) -> str:
        """Generate unittest test code."""
        source_path = Path(source_file)
        module_name = source_path.stem
        
        code = f'''"""
Generated test cases for {source_path.name}
Auto-generated by AI Test Generator
"""

import unittest
from {module_name} import *


class Test{module_name.title()}(unittest.TestCase):
    """Test cases for {module_name}."""
    
    def setUp(self):
        """Set up test fixtures."""
        pass
    
    def tearDown(self):
        """Clean up after tests."""
        pass

'''
        
        # Generate test methods
        for i, test_case in enumerate(test_cases):
            code += self._generate_unittest_test_method(test_case, i)
            code += "\n"
        
        code += '''

if __name__ == '__main__':
    unittest.main()
'''
        
        return code
    
    def _generate_unittest_test_method(
        self,
        test_case: Dict[str, Any],
        index: int
    ) -> str:
        """Generate a single unittest test method."""
        func_name = test_case.get('function', 'unknown')
        test_type = test_case.get('type', 'general')
        description = test_case.get('description', '')
        params = test_case.get('params', {})
        expected = test_case.get('expected', 'success')
        
        test_name = f"test_{func_name}_{test_type}_{index}"
        test_name = test_name.replace(' ', '_').replace('-', '_')
        
        code = f'    def {test_name}(self):\n'
        code += f'        """{description}"""\n'
        
        if 'raises' in expected or 'exception' in test_type.lower():
            exception_type = self._extract_exception_type(expected, test_case)
            code += f'        with self.assertRaises({exception_type}):\n'
            code += f'            {func_name}('
            code += self._format_params(params)
            code += ')\n'
        else:
            code += f'        result = {func_name}('
            code += self._format_params(params)
            code += ')\n'
            code += '        self.assertIsNotNone(result)\n'
        
        return code
    
    def render_user_story_tests(
        self,
        user_story: str,
        scenarios: List[Dict[str, Any]],
        framework: str = 'pytest'
    ) -> str:
        """
        Render tests from user story scenarios.
        
        Args:
            user_story: Original user story
            scenarios: Test scenarios from parser
            framework: Test framework
            
        Returns:
            Generated test code
        """
        code = f'''"""
Test cases generated from user story:
{user_story}

Auto-generated by AI Test Generator
"""

import pytest


'''
        
        for i, scenario in enumerate(scenarios):
            code += self._generate_scenario_test(scenario, i)
            code += "\n\n"
        
        return code
    
    def _generate_scenario_test(
        self,
        scenario: Dict[str, Any],
        index: int
    ) -> str:
        """Generate test from user story scenario."""
        title = scenario.get('title', f'scenario_{index}')
        given = scenario.get('given', '')
        when = scenario.get('when', '')
        then = scenario.get('then', '')
        
        test_name = f"test_{title.lower().replace(' ', '_')}"
        
        code = f'def {test_name}():\n'
        code += f'    """\n'
        code += f'    Scenario: {title}\n'
        code += f'    Given {given}\n'
        code += f'    When {when}\n'
        code += f'    Then {then}\n'
        code += f'    """\n'
        code += '    # TODO: Implement test scenario\n'
        code += '    # Given\n'
        code += f'    # {given}\n'
        code += '    \n'
        code += '    # When\n'
        code += f'    # {when}\n'
        code += '    \n'
        code += '    # Then\n'
        code += f'    # {then}\n'
        code += '    assert True  # Replace with actual assertions\n'
        
        return code
